services:
  mjpeg-server:
    build: .
    env_file:
      - .env.local
    restart: always
    ports:
      - 8080:8080/tcp
      - 8081:8081/udp
    environment:
      MJPEG_SERVER_ADDRESS_WEB: ":8080"
      MJPEG_SERVER_ADDRESS_UDP: ":8081"
      MJPEG_SERVER_FRAMERATE: 25
    #deploy:
    #  restart_policy:
    #    condition: any
    #    delay: 5s
